### ISSUE TITLE
Package new release for Puppet Forge

### ISSUE THREAD

**Issue by Areson** [Areson/xml_fragment#10]
There have been several pull requests, so it's time to package a new release. This is a reminder to test, package, and deploy a new version of the module.

**Comment by kennethacurtis** [comment]
Hello, do you have an idea when the new version will be released to the forge? Thanks

**Comment by Areson** [comment]
Hopefully in the next few weeks. I've been trying to get to this and wrap up a few outstanding issues.

**Comment by llowder** [comment]
Just wanted to bump this and see if there was an update on the new release.

**Comment by Areson** [comment]
@alexjfisher @llowder I'm aiming at putting this on the forge today. My spam folder started eating all of my GitHub notifications and that really messed up my scheduling. Sorry for the long delay.
