### ISSUE TITLE
Duplicates, then newer versions fail

### ISSUE THREAD

**Issue by kwstone14** [Areson/xml_fragment#11]
We've been using version 1.0.2, which looks like commit 898890e, for a while now to add xml code to a Newrelic config file. The problem: while the readme file says:

The default behavior of the xml_fragment resource is to create or update the tag indicated by the xpath parameter. If the tag does not exist it will be created. If it exists the value and attributes of the tag will be updated if needed.

What I'm seeing is that the entire set of entries is added to what's already in the area that's being managed by puppet every time a puppet run is done. The servers in question have about 30 entries to be added. If I start from blank in the managed section, the first run will put the 30 entries in. On the second run, 30 more entries are added, and there are now two copies of each entry in that section now. On the third run, 30 more are added so that now there are 90 lines and 3 of each entry. Etc.

I tried to move to a newer commit to see if maybe this issue had been fixed. Commit 7db084f doesn't have a problem. But starting with commit ba835df, puppet runs fail with

Error: /Stage[main]/Newrelic::Dotnet_apm/Xml_fragment[NewRelic APM LicenseKey]: Could not evaluate: undefined method `key?' for nil:NilClass
Error: /Stage[main]/Newrelic::Dotnet_apm/Xml_fragment[NewRelic APM App Name]: Could not evaluate: undefined method `key?' for nil:NilClass

None of the Puppet manifests that call xml_fragment have changed any of the parameters, and it looks from the readme file that there are no new requirements for calling this type.

I can provide more specific code if someone has some ideas. But again: the only thing I'm changing is the commit of xml_fragment. Everything else is the same.

**Comment by kwstone14** [comment]
I dug into this some more. The error occurs in concert with changing instances of has_key? with key?. I'm looking specifically at lib/puppet/provider/xml_fragment/xml_fragment.rb, and it's crashing in def exists? The code works fine while using versions that still have has_key? in use. Once key? is put in there instead, then the undefined method messages start happening.

**Comment by kwstone14** [comment]
It just occurred to me that it could be the version of puppetserver and ruby that we're on. Maybe a chance that the solution would be to upgrade both?

rpm -qa puppetserver
puppetserver-2.5.0-1.el7.noarch

ruby -v
ruby 2.1.9p490 (2016-03-30 revision 54437) [x86_64-linux]

**Comment by Areson** [comment]
I don't think that it is. Looking at the code it looks like a pull request modified the keys on a class variable hash, which broke it. I reverted it. Try the the code in the Areson-1.0.3 branch, as that is the release candidate for the next version. I just adjusted this there.

**Comment by kwstone14** [comment]
The branch you just created got past the nil:NilClass failure. So we're back to the issue of the module appending the same lines in the managed section with each puppet run. Below is the instrumentation/applications section of the file we're using it on. I started out by emptying out the applications section, then running puppet agent -t twice. The result is two copies of every application line. If I run it again, another batch will be added.

  <instrumentation>
    <applications>
      <application name='ATStatsProcessor.exe'/>
      <application name='CarfaxReportService.exe'/>
      <application name='CompellingDescriptions.Service.exe'/>
      <application name='Elasticsearch.Refresh.exe'/>
      <application name='Ftc.Generator.Daemon.exe'/>
      <application name='ImageImporter.exe'/>
      <application name='Integration.Chrome.Service.exe'/>
      <application name='Integration.Ebay.Service.exe'/>
      <application name='ImageScraper.exe'/>
      <application name='Va.Mail.Gatherer.exe'/>
      <application name='Mail.Processor.exe'/>
      <application name='Marketing.CacheRefresh.exe'/>
      <application name='Notification.NotificationDaemon.exe'/>
      <application name='Pricing.Service.exe'/>
      <application name='Radar.Ranker.exe'/>
      <application name='Integration.Manheim.BMWBuildData.exe'/>
      <application name='Integration.Homenet.Load.exe'/>
      <application name='Integration.Manheim.ConditionReport.Load.exe'/>
      <application name='AuctionEdgeImporter.exe'/>
      <application name='ProfitTime.QueueProcessor.exe'/>
      <application name='WatcherService.exe'/>
      <application name='Vehicle.Photo.Deleter.exe'/>
      <application name='Vehicle.Photo.Publisher.exe'/>
      <application name='Conquest.MarketMonitor.exe'/>
      <application name='TransferAdvantageCrossMarket.QueueProcessor.exe'/>
      <application name='Valuation.AuctionVehicleCleanup.exe'/>
      <application name='RemoteLoggingService.exe'/>
      <application name='ATStatsProcessor.exe'/>
      <application name='CarfaxReportService.exe'/>
      <application name='CompellingDescriptions.Service.exe'/>
      <application name='Elasticsearch.Refresh.exe'/>
      <application name='Ftc.Generator.Daemon.exe'/>
      <application name='ImageImporter.exe'/>
      <application name='Integration.Chrome.Service.exe'/>
      <application name='Integration.Ebay.Service.exe'/>
      <application name='ImageScraper.exe'/>
      <application name='Va.Mail.Gatherer.exe'/>
      <application name='Mail.Processor.exe'/>
      <application name='Marketing.CacheRefresh.exe'/>
      <application name='Notification.NotificationDaemon.exe'/>
      <application name='Pricing.Service.exe'/>
      <application name='Radar.Ranker.exe'/>
      <application name='Integration.Manheim.BMWBuildData.exe'/>
      <application name='Integration.Homenet.Load.exe'/>
      <application name='Integration.Manheim.ConditionReport.Load.exe'/>
      <application name='AuctionEdgeImporter.exe'/>
      <application name='ProfitTime.QueueProcessor.exe'/>
      <application name='WatcherService.exe'/>
      <application name='Vehicle.Photo.Deleter.exe'/>
      <application name='Vehicle.Photo.Publisher.exe'/>
      <application name='Conquest.MarketMonitor.exe'/>
      <application name='TransferAdvantageCrossMarket.QueueProcessor.exe'/>
      <application name='Valuation.AuctionVehicleCleanup.exe'/>
      <application name='RemoteLoggingService.exe'/>
    </applications>
  </instrumentation>

**Comment by kwstone14** [comment]
<instrumentation>
    <applications>
      <application name='ATStatsProcessor.exe'/>
      <application name='CarfaxReportService.exe'/>
      <application name='CompellingDescriptions.Service.exe'/>
      <application name='Elasticsearch.Refresh.exe'/>
      <application name='Ftc.Generator.Daemon.exe'/>
      <application name='ImageImporter.exe'/>
      <application name='Integration.Chrome.Service.exe'/>
      <application name='Integration.Ebay.Service.exe'/>
      <application name='ImageScraper.exe'/>
      <application name='Va.Mail.Gatherer.exe'/>
      <application name='Mail.Processor.exe'/>
      <application name='Marketing.CacheRefresh.exe'/>
      <application name='Notification.NotificationDaemon.exe'/>
      <application name='Pricing.Service.exe'/>
      <application name='Radar.Ranker.exe'/>
      <application name='Integration.Manheim.BMWBuildData.exe'/>
      <application name='Integration.Homenet.Load.exe'/>
      <application name='Integration.Manheim.ConditionReport.Load.exe'/>
      <application name='AuctionEdgeImporter.exe'/>
      <application name='ProfitTime.QueueProcessor.exe'/>
      <application name='WatcherService.exe'/>
      <application name='Vehicle.Photo.Deleter.exe'/>
      <application name='Vehicle.Photo.Publisher.exe'/>
      <application name='Conquest.MarketMonitor.exe'/>
      <application name='TransferAdvantageCrossMarket.QueueProcessor.exe'/>
      <application name='Valuation.AuctionVehicleCleanup.exe'/>
      <application name='RemoteLoggingService.exe'/>
      <application name='ATStatsProcessor.exe'/>
      <application name='CarfaxReportService.exe'/>
      <application name='CompellingDescriptions.Service.exe'/>
      <application name='Elasticsearch.Refresh.exe'/>
      <application name='Ftc.Generator.Daemon.exe'/>
      <application name='ImageImporter.exe'/>
      <application name='Integration.Chrome.Service.exe'/>
      <application name='Integration.Ebay.Service.exe'/>
      <application name='ImageScraper.exe'/>
      <application name='Va.Mail.Gatherer.exe'/>
      <application name='Mail.Processor.exe'/>
      <application name='Marketing.CacheRefresh.exe'/>
      <application name='Notification.NotificationDaemon.exe'/>
      <application name='Pricing.Service.exe'/>
      <application name='Radar.Ranker.exe'/>
      <application name='Integration.Manheim.BMWBuildData.exe'/>
      <application name='Integration.Homenet.Load.exe'/>
      <application name='Integration.Manheim.ConditionReport.Load.exe'/>
      <application name='AuctionEdgeImporter.exe'/>
      <application name='ProfitTime.QueueProcessor.exe'/>
      <application name='WatcherService.exe'/>
      <application name='Vehicle.Photo.Deleter.exe'/>
      <application name='Vehicle.Photo.Publisher.exe'/>
      <application name='Conquest.MarketMonitor.exe'/>
      <application name='TransferAdvantageCrossMarket.QueueProcessor.exe'/>
      <application name='Valuation.AuctionVehicleCleanup.exe'/>
      <application name='RemoteLoggingService.exe'/>
    </applications>
  </instrumentation>

**Comment by Areson** [comment]
Can you give me some example config and output to review please?

**Comment by kwstone14** [comment]
[newrelic.config.txt](https://github.com/Areson/xml_fragment/files/3798871/newrelic.config.txt)

**Comment by Areson** [comment]
What does the config for the xml_fragment module look like for the section in question?

**Comment by kwstone14** [comment]
I'm including the clause in our puppet code that makes the call to xml_fragment for this section of the newrelic.config file. 
[UseOfXmlFragment.txt](https://github.com/Areson/xml_fragment/files/3798883/UseOfXmlFragment.txt)

**Comment by Areson** [comment]
In your xpath, trying putting single quotes around the string of the name attribute you are looking for:
`/configuration/instrumentation/applications/application[@name='${executable}']`

**Comment by kwstone14** [comment]
Working on it; will let you know shortly

**Comment by kwstone14** [comment]
Looks like '${executable}' did it. I emptied out the applications section and ran puppet agent -t three times. The first time added the applications, and the 2nd and 3rd didn't add anything else. 

I'll get that change committed to our puppet code base. Thanks for the catch on it. I think we can close this issue. I'll watch on your merge of the branch Areson-1.0.3 and incorporate it.
