### ISSUE TITLE
When using `purge` file is overwritten on every puppet run

### ISSUE THREAD

**Issue by alexjfisher** [Areson/xml_fragment#14]
I've noticed that my xml file is being overwritten (with no changes) on every puppet run.  This has a side-effect of causing my application server (mono aspnet in this case) to restart the application every 30 minutes.
I think it is `purge_tags` that is always calling `save`.

**Comment by Areson** [comment]
Will review.

**Comment by Areson** [comment]
Take a look at the `development` branch to see if this resolves the issue for you. I've staged all of the changes going into the 1.0.3 release there.

**Comment by Areson** [comment]
@alexjfisher ^

**Comment by alexjfisher** [comment]
@Areson Sorry it's taken so long, but I've finally found a moment to test out your fix.  Looks great!

**Comment by alexjfisher** [comment]
@Areson - Do you need any help getting a release out? @llowder was asking about this module over on slack and is interested too.
