### ISSUE TITLE
Attributes are not added to node if it already exists but has no attributes

### ISSUE THREAD

**Issue by rpolley** [Areson/xml_fragment#18]
I was trying to use this to edit some xml based config files, but I ran into an issue: consider the following xml file `somefile.xml`
```xml
<config>
  <setting>
</config>
```
And the following manifest
```puppet
xml_fragment { 'set setting.value to 1` :
  ensure => 'present'
  path => 'somefile.xml',
  xpath => '/config/setting',
  content => {
    attributes => {
      value => 1
    }
  }
```
Will result in an unchanged somefile.xml, however if the somefile.xml file was instead:
```xml
<config>
  <setting value=2>
</config>
```
You would instead end up with
```xml
<config>
  <setting value=1>
</config>
```
This is of course a simplified example, but it causes bugs when you try to use this to edit IIS config files, which use the convention of having attributes represent leaf settings that can be assigned values and the absence of a given attribute means that the setting the attribute represents takes its default value.

**Comment by rpolley** [comment]
I believe this is caused by https://github.com/Areson/xml_fragment/blob/f9873c873d9b5572c7160ddc34f4843fd2e3b509/lib/puppet/provider/xml_fragment/xml_fragment.rb#L188 which causes the provider matches method to not compare the should value for the attributes to the is value of the attributes if the is value is nil, which is the case if the tag exists but does not have attributes

**Comment by Areson** [comment]
I will try and review this in the next week.

**Comment by Areson** [comment]
@rpolley You were spot on. Adding a check for the case where the definition has attributes defined but the existing element doesn't have any. Tested it on my end and it appears to work, but go ahead and pull from the development branch and give if a go before I package it up.

**Comment by Areson** [comment]
@rpolley Bump

**Comment by 1WindowsPuppetAdmin** [comment]
@Areson - can you merge this in? i don't think we need to wait on rpolley as long as you tested it and it works. I've been waiting for this fix as well.

**Comment by rpolley** [comment]
@Areson seconding this, @1WindowsPuppetAdmin is probably in a better position than I am to validate that this works anyway.

**Comment by Areson** [comment]
I've released the updated version on the forge. Thanks for your patience.
